### ISSUE TITLE
support deploy chaosd by TiUP

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#108]
Now we can only deploy Chaosd manually. If you have a lot of servers, it takes a lot of work to deploy it.
[TiUP](https://github.com/pingcap/tiup) is a cluster operation and maintenance tool, we can use it to deploy Chaosd.

**Comment by rouke-broersma** [comment]
TiUP seems to be a tool to manage https://docs.pingcap.com/tidb which seems to be some kind of distributed database, I'm not sure if you linked to the wrong tool but to me it does not seem like a good fit for deploying chaosd.

**Comment by WangXiangUSTC** [comment]
The link is right. In fact, TiUP is not only used for TiDB, it is a package manager tool. You can execute `tiup list --all` to see all the components which are supported by TiUP.

By the way, we are planning to implement the deployment of chaosd in [chaosctl](https://chaos-mesh.org/docs/2.0.7/chaosctl-tool/), which is a tool of Chaos Mesh.

**Comment by WangXiangUSTC** [comment]
This issue can be closed.
