### ISSUE TITLE
请问下带简单web界面的工具有github地址吗？类似chaos-mesh的那种。

### ISSUE THREAD

**Issue by pengliangyou** [chaos-mesh/chaosd#114]
Thank you!

**Comment by YangKeao** [comment]
@iguoyr and @WangXiangUSTC is working on managing chaosd injection on Chaos Mesh (and its dashboard), which is the `PhysicalMachineChaos`. You can find the documents [here](https://chaos-mesh.org/zh/docs/next/simulate-physical-machine-chaos/). If you don't have an existing kubernetes cluster to deploy chaos mesh, we will find some ways to deploy and setup chaos mesh (and dashboard) without an existing cluster in the future, but this attempt hasn't started.

In Chinese:

@iguoyr 和 @WangXiangUSTC 正在制作通过 Chaos Mesh （以及它的 Dashboard）来管理 chaosd 的功能，这个功能就是 `PhysicalMachineChaos`。它的基本功能已经可用，可以在 [这里](https://chaos-mesh.org/zh/docs/next/simulate-physical-machine-chaos/) 看到它的文档；权限验证等功能正在开发。问题是，如果你没有一个现成的 Kubernetes 集群，部署 Chaos Mesh 可能会很麻烦（其实如果使用 k3s 或类似环境，也非常简单 :smile: ）。在将来我们会提供一个脱离 Kubernetes 集群部署 Chaos Mesh 的方法，但还没有规划它的尝试/开发时间。
