### ISSUE TITLE
Unknown shorthand 'd' when simulating disk fill

### ISSUE THREAD

**Issue by ThreadDao** [chaos-mesh/chaosd#143]
I try to inject disk fault with cmd `chaosd` attack disk fill -c 50 -d -f` and get the unknown error. My chaosd version is latest, and chaosd-v1.0.0 also has this problem.  By the way the flag d is described in the official documentation.
```
$ chaosd attack disk fill -c 50 -d -f
Error: unknown shorthand flag: 'd' in -d
Usage:
  chaosd attack disk fill [flags]

Flags:
  -f, --fallocate        fill disk by fallocate instead of dd (default true)
  -h, --help             help for fill
  -p, --path string      'path' specifies the location to fill data in.If path not provided, a temp file will be generated and deleted immediately after data filled in or allocated
  -c, --percent string   'percent' how many percent data of disk will fill in the file path
  -s, --size string      'size' specifies how many units of data will fill in the file path.'unit' specifies the unit of data, support c=1, w=2, b=512, kB=1000, K=1024, MB=1000*1000,M=1024*1024, , GB=1000*1000*1000, G=1024*1024*1024 BYTESexample : 1M | 512kB

Global Flags:
      --log-level string   the log level of chaosd. The value can be 'debug', 'info', 'warn' and 'error'
      --uid string         the experiment ID

Error: unknown shorthand flag: 'd' in -d
```
official documentation:
![image](https://user-images.githubusercontent.com/27288593/158772081-a419260b-eb79-422a-89aa-cd8199b51edf.png)

**Comment by WangXiangUSTC** [comment]
It seems that it's not supported in v1.0.0, you can try the v1.1.1?

**Comment by ThreadDao** [comment]
@WangXiangUSTC Thanks for your reply. What's the difference between the latest and v1.1.1?

**Comment by Andrewmatilde** [comment]
In the last version , the temp file will not be auto delete and you can use disk recover to delete it.

**Comment by ThreadDao** [comment]
> In the last version , the temp file will not be auto delete and you can use disk recover to delete it.

Ok, thank you. I will close the issue
