### ISSUE TITLE
What version of Chaod should I select under Chaos-Mesh V2.1.5

### ISSUE THREAD

**Issue by nioshield** [chaos-mesh/chaosd#166]
In my environment, i use Chaos-Mesh V2.1.5,Which version should I choose if I install Chaod

Are there documents for Chaod and Chaos-Mesh about version depends ?

**Comment by YangKeao** [comment]
@WangXiangUSTC 

@STRRL also related with Release Cycle.

**Comment by WangXiangUSTC** [comment]
https://chaos-mesh.org/docs/next/simulate-physical-machine-chaos/#introduction-to-physicalmachinechaos
here is a version map with Chaos Mesh and Chaosd, PTAL
