### ISSUE TITLE
add some test for process chaos

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#19]
We need to add some tests for process chaos, like integration test or unit test, can refer to https://github.com/chaos-mesh/chaosd/tree/main/test/integration_test

**Comment by AsterNighT** [comment]
I'm a bit intereted in this. I am wondering if I may introduce another binary to help test it?

**Comment by WangXiangUSTC** [comment]
> I'm a bit intereted in this. I am wondering if I may introduce another binary to help test it?

It's OK
