### ISSUE TITLE
support IO chaos on disk

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#28]
Note: It is different from the IO chaos in Chaos Mesh

This feature includes the following capabilities：
- emulation of real read and write on disk
- fill the disk

**Comment by WangXiangUSTC** [comment]
@Andrewmatilde PTAL

**Comment by Andrewmatilde** [comment]
OK,I agree with you.

**Comment by YangKeao** [comment]
There is another problem. @Andrewmatilde  @WangXiangUSTC Do you think Chaos Mesh should also provide similar functions? Should we brought this feature to `chaos-daemon`?

**Comment by WangXiangUSTC** [comment]
> There is another problem. @Andrewmatilde @WangXiangUSTC Do you think Chaos Mesh should also provide similar functions? Should we brought this feature to `chaos-daemon`?

I think we can do this
