### ISSUE TITLE
support DNS type under Network attack 

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaosd#41]
This feature maybe includes:
- [x] update the address of the DNS server to a wrong value 
- [ ] map a host with a wrong address

This can be implement by modify the file `/etc/hosts` and `/etc/resolv.conf`

**Comment by AsterNighT** [comment]
A typo, s/suport/support/

**Comment by WangXiangUSTC** [comment]
> A typo, s/suport/support/

the title updated 😄
