### ISSUE TITLE
Distribute binaries via Homebrew

### ISSUE THREAD

**Issue by KeisukeYamashita** [chaos-mesh/chaosd#45]
## What

I'm macOS user and I will be happy if I can install and manage the binary via [Homebrew](https://brew.sh/).
Many tools release it via Homebrew and it's very friendly because we can easily install or uninstall easily.

## Ideas

```console
$ brew tap chaos-mesh/tap
$ brew install chaosctl
```

**Comment by STRRL** [comment]
I am afraid of `chaosd` could not works well on macOS, because many features is based on Linux.

But I think distributing `chaosctl` via homebrew might be a good choice.

**Comment by YangKeao** [comment]
> I am afraid of `chaosd` could not works well on macOS, because many features is based on Linux.
> 
> But I think distributing `chaosctl` via homebrew might be a good choice.

I'm really willing to package `ebuild` (on gentoo) and `rpm` (on Fedora 34) for `chaosctl`  :smile_cat:

**Comment by KeisukeYamashita** [comment]
@STRRL 

> But I think distributing chaosctl via homebrew might be a good choice.

Ah, sorry, I was trying to mention `chaosctl` not `chaosd` 🙇  Fixed the issue title and the noctent.

**Comment by KeisukeYamashita** [comment]
This issue is in the wrong place,closing.
